# Generated by Django 4.0.2 on 2022-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='contact',
        ),
        migrations.AddField(
            model_name='reference',
            name='relation',
            field=models.CharField(default='Fred', max_length=48),
            preserve_default=False,
        ),
    ]
